---
apiVersion: v1
kind: Service
metadata:
  name: staragile-service
  labels:
    run: staragile
spec:
  type: NodePort
  selector:
    run: staragile
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  
