apiVersion: v1
kind: Service
metadata:
  name: staragile-service
  labels:
    app: staragile
spec:
  selector:
    app: rstaragile

  ports:
    - port: 8090
      targetPort: 8081

  type: LoadBalancer
